//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace DrRobot.JaguarControl {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("RobotConfig")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class RobotConfig : global::System.Data.DataSet {
        
        private RobotConfigTableDataTable tableRobotConfigTable;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public RobotConfig() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected RobotConfig(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["RobotConfigTable"] != null)) {
                    base.Tables.Add(new RobotConfigTableDataTable(ds.Tables["RobotConfigTable"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public RobotConfigTableDataTable RobotConfigTable {
            get {
                return this.tableRobotConfigTable;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            RobotConfig cln = ((RobotConfig)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["RobotConfigTable"] != null)) {
                    base.Tables.Add(new RobotConfigTableDataTable(ds.Tables["RobotConfigTable"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableRobotConfigTable = ((RobotConfigTableDataTable)(base.Tables["RobotConfigTable"]));
            if ((initTable == true)) {
                if ((this.tableRobotConfigTable != null)) {
                    this.tableRobotConfigTable.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "RobotConfig";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/RobotConfig.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableRobotConfigTable = new RobotConfigTableDataTable();
            base.Tables.Add(this.tableRobotConfigTable);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeRobotConfigTable() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            RobotConfig ds = new RobotConfig();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void RobotConfigTableRowChangeEventHandler(object sender, RobotConfigTableRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class RobotConfigTableDataTable : global::System.Data.TypedTableBase<RobotConfigTableRow> {
            
            private global::System.Data.DataColumn columnRobotID;
            
            private global::System.Data.DataColumn columnRobotIP;
            
            private global::System.Data.DataColumn columnPort1;
            
            private global::System.Data.DataColumn columnPort2;
            
            private global::System.Data.DataColumn columnGPSIP;
            
            private global::System.Data.DataColumn columnGPSPort;
            
            private global::System.Data.DataColumn columnCameraIP;
            
            private global::System.Data.DataColumn columnCameraPort;
            
            private global::System.Data.DataColumn columnCameraPWD;
            
            private global::System.Data.DataColumn columnCameraUser;
            
            private global::System.Data.DataColumn columnAimCameraIP;
            
            private global::System.Data.DataColumn columnAimCameraPort;
            
            private global::System.Data.DataColumn columnAimCameraPWD;
            
            private global::System.Data.DataColumn columnAimCameraUser;
            
            private global::System.Data.DataColumn columnIMUIP;
            
            private global::System.Data.DataColumn columnIMUPort;
            
            private global::System.Data.DataColumn columnLaserRangeIP;
            
            private global::System.Data.DataColumn columnLaserRangePort;
            
            private global::System.Data.DataColumn columnGoogleEarthStartLat;
            
            private global::System.Data.DataColumn columnGoogleEarthStartLong;
            
            private global::System.Data.DataColumn columnRobotType;
            
            private global::System.Data.DataColumn columnMotorDir;
            
            private global::System.Data.DataColumn columnWheel_CNT;
            
            private global::System.Data.DataColumn columnWheel_R;
            
            private global::System.Data.DataColumn columnWheel_DIS;
            
            private global::System.Data.DataColumn columnMinDiffPWM;
            
            private global::System.Data.DataColumn columnDrvThrottle;
            
            private global::System.Data.DataColumn columnTurnDir;
            
            private global::System.Data.DataColumn columnTurnK;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RobotConfigTableDataTable() {
                this.TableName = "RobotConfigTable";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal RobotConfigTableDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected RobotConfigTableDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn RobotIDColumn {
                get {
                    return this.columnRobotID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn RobotIPColumn {
                get {
                    return this.columnRobotIP;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Port1Column {
                get {
                    return this.columnPort1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Port2Column {
                get {
                    return this.columnPort2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn GPSIPColumn {
                get {
                    return this.columnGPSIP;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn GPSPortColumn {
                get {
                    return this.columnGPSPort;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CameraIPColumn {
                get {
                    return this.columnCameraIP;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CameraPortColumn {
                get {
                    return this.columnCameraPort;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CameraPWDColumn {
                get {
                    return this.columnCameraPWD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CameraUserColumn {
                get {
                    return this.columnCameraUser;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn AimCameraIPColumn {
                get {
                    return this.columnAimCameraIP;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn AimCameraPortColumn {
                get {
                    return this.columnAimCameraPort;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn AimCameraPWDColumn {
                get {
                    return this.columnAimCameraPWD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn AimCameraUserColumn {
                get {
                    return this.columnAimCameraUser;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn IMUIPColumn {
                get {
                    return this.columnIMUIP;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn IMUPortColumn {
                get {
                    return this.columnIMUPort;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn LaserRangeIPColumn {
                get {
                    return this.columnLaserRangeIP;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn LaserRangePortColumn {
                get {
                    return this.columnLaserRangePort;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn GoogleEarthStartLatColumn {
                get {
                    return this.columnGoogleEarthStartLat;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn GoogleEarthStartLongColumn {
                get {
                    return this.columnGoogleEarthStartLong;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn RobotTypeColumn {
                get {
                    return this.columnRobotType;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn MotorDirColumn {
                get {
                    return this.columnMotorDir;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Wheel_CNTColumn {
                get {
                    return this.columnWheel_CNT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Wheel_RColumn {
                get {
                    return this.columnWheel_R;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn Wheel_DISColumn {
                get {
                    return this.columnWheel_DIS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn MinDiffPWMColumn {
                get {
                    return this.columnMinDiffPWM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DrvThrottleColumn {
                get {
                    return this.columnDrvThrottle;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TurnDirColumn {
                get {
                    return this.columnTurnDir;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TurnKColumn {
                get {
                    return this.columnTurnK;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RobotConfigTableRow this[int index] {
                get {
                    return ((RobotConfigTableRow)(this.Rows[index]));
                }
            }
            
            public event RobotConfigTableRowChangeEventHandler RobotConfigTableRowChanging;
            
            public event RobotConfigTableRowChangeEventHandler RobotConfigTableRowChanged;
            
            public event RobotConfigTableRowChangeEventHandler RobotConfigTableRowDeleting;
            
            public event RobotConfigTableRowChangeEventHandler RobotConfigTableRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddRobotConfigTableRow(RobotConfigTableRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RobotConfigTableRow AddRobotConfigTableRow(
                        string RobotID, 
                        string RobotIP, 
                        int Port1, 
                        int Port2, 
                        string GPSIP, 
                        int GPSPort, 
                        string CameraIP, 
                        int CameraPort, 
                        string CameraPWD, 
                        string CameraUser, 
                        string AimCameraIP, 
                        int AimCameraPort, 
                        string AimCameraPWD, 
                        string AimCameraUser, 
                        string IMUIP, 
                        int IMUPort, 
                        string LaserRangeIP, 
                        int LaserRangePort, 
                        double GoogleEarthStartLat, 
                        double GoogleEarthStartLong, 
                        string RobotType, 
                        int MotorDir, 
                        int Wheel_CNT, 
                        double Wheel_R, 
                        double Wheel_DIS, 
                        double MinDiffPWM, 
                        double DrvThrottle, 
                        int TurnDir, 
                        double TurnK) {
                RobotConfigTableRow rowRobotConfigTableRow = ((RobotConfigTableRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        RobotID,
                        RobotIP,
                        Port1,
                        Port2,
                        GPSIP,
                        GPSPort,
                        CameraIP,
                        CameraPort,
                        CameraPWD,
                        CameraUser,
                        AimCameraIP,
                        AimCameraPort,
                        AimCameraPWD,
                        AimCameraUser,
                        IMUIP,
                        IMUPort,
                        LaserRangeIP,
                        LaserRangePort,
                        GoogleEarthStartLat,
                        GoogleEarthStartLong,
                        RobotType,
                        MotorDir,
                        Wheel_CNT,
                        Wheel_R,
                        Wheel_DIS,
                        MinDiffPWM,
                        DrvThrottle,
                        TurnDir,
                        TurnK};
                rowRobotConfigTableRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowRobotConfigTableRow);
                return rowRobotConfigTableRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                RobotConfigTableDataTable cln = ((RobotConfigTableDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new RobotConfigTableDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnRobotID = base.Columns["RobotID"];
                this.columnRobotIP = base.Columns["RobotIP"];
                this.columnPort1 = base.Columns["Port1"];
                this.columnPort2 = base.Columns["Port2"];
                this.columnGPSIP = base.Columns["GPSIP"];
                this.columnGPSPort = base.Columns["GPSPort"];
                this.columnCameraIP = base.Columns["CameraIP"];
                this.columnCameraPort = base.Columns["CameraPort"];
                this.columnCameraPWD = base.Columns["CameraPWD"];
                this.columnCameraUser = base.Columns["CameraUser"];
                this.columnAimCameraIP = base.Columns["AimCameraIP"];
                this.columnAimCameraPort = base.Columns["AimCameraPort"];
                this.columnAimCameraPWD = base.Columns["AimCameraPWD"];
                this.columnAimCameraUser = base.Columns["AimCameraUser"];
                this.columnIMUIP = base.Columns["IMUIP"];
                this.columnIMUPort = base.Columns["IMUPort"];
                this.columnLaserRangeIP = base.Columns["LaserRangeIP"];
                this.columnLaserRangePort = base.Columns["LaserRangePort"];
                this.columnGoogleEarthStartLat = base.Columns["GoogleEarthStartLat"];
                this.columnGoogleEarthStartLong = base.Columns["GoogleEarthStartLong"];
                this.columnRobotType = base.Columns["RobotType"];
                this.columnMotorDir = base.Columns["MotorDir"];
                this.columnWheel_CNT = base.Columns["Wheel_CNT"];
                this.columnWheel_R = base.Columns["Wheel_R"];
                this.columnWheel_DIS = base.Columns["Wheel_DIS"];
                this.columnMinDiffPWM = base.Columns["MinDiffPWM"];
                this.columnDrvThrottle = base.Columns["DrvThrottle"];
                this.columnTurnDir = base.Columns["TurnDir"];
                this.columnTurnK = base.Columns["TurnK"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnRobotID = new global::System.Data.DataColumn("RobotID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRobotID);
                this.columnRobotIP = new global::System.Data.DataColumn("RobotIP", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRobotIP);
                this.columnPort1 = new global::System.Data.DataColumn("Port1", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPort1);
                this.columnPort2 = new global::System.Data.DataColumn("Port2", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPort2);
                this.columnGPSIP = new global::System.Data.DataColumn("GPSIP", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnGPSIP);
                this.columnGPSPort = new global::System.Data.DataColumn("GPSPort", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnGPSPort);
                this.columnCameraIP = new global::System.Data.DataColumn("CameraIP", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCameraIP);
                this.columnCameraPort = new global::System.Data.DataColumn("CameraPort", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCameraPort);
                this.columnCameraPWD = new global::System.Data.DataColumn("CameraPWD", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCameraPWD);
                this.columnCameraUser = new global::System.Data.DataColumn("CameraUser", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCameraUser);
                this.columnAimCameraIP = new global::System.Data.DataColumn("AimCameraIP", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAimCameraIP);
                this.columnAimCameraPort = new global::System.Data.DataColumn("AimCameraPort", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAimCameraPort);
                this.columnAimCameraPWD = new global::System.Data.DataColumn("AimCameraPWD", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAimCameraPWD);
                this.columnAimCameraUser = new global::System.Data.DataColumn("AimCameraUser", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAimCameraUser);
                this.columnIMUIP = new global::System.Data.DataColumn("IMUIP", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIMUIP);
                this.columnIMUPort = new global::System.Data.DataColumn("IMUPort", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIMUPort);
                this.columnLaserRangeIP = new global::System.Data.DataColumn("LaserRangeIP", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLaserRangeIP);
                this.columnLaserRangePort = new global::System.Data.DataColumn("LaserRangePort", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLaserRangePort);
                this.columnGoogleEarthStartLat = new global::System.Data.DataColumn("GoogleEarthStartLat", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnGoogleEarthStartLat);
                this.columnGoogleEarthStartLong = new global::System.Data.DataColumn("GoogleEarthStartLong", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnGoogleEarthStartLong);
                this.columnRobotType = new global::System.Data.DataColumn("RobotType", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRobotType);
                this.columnMotorDir = new global::System.Data.DataColumn("MotorDir", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMotorDir);
                this.columnWheel_CNT = new global::System.Data.DataColumn("Wheel_CNT", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnWheel_CNT);
                this.columnWheel_R = new global::System.Data.DataColumn("Wheel_R", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnWheel_R);
                this.columnWheel_DIS = new global::System.Data.DataColumn("Wheel_DIS", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnWheel_DIS);
                this.columnMinDiffPWM = new global::System.Data.DataColumn("MinDiffPWM", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMinDiffPWM);
                this.columnDrvThrottle = new global::System.Data.DataColumn("DrvThrottle", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDrvThrottle);
                this.columnTurnDir = new global::System.Data.DataColumn("TurnDir", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTurnDir);
                this.columnTurnK = new global::System.Data.DataColumn("TurnK", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTurnK);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RobotConfigTableRow NewRobotConfigTableRow() {
                return ((RobotConfigTableRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new RobotConfigTableRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(RobotConfigTableRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.RobotConfigTableRowChanged != null)) {
                    this.RobotConfigTableRowChanged(this, new RobotConfigTableRowChangeEvent(((RobotConfigTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.RobotConfigTableRowChanging != null)) {
                    this.RobotConfigTableRowChanging(this, new RobotConfigTableRowChangeEvent(((RobotConfigTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.RobotConfigTableRowDeleted != null)) {
                    this.RobotConfigTableRowDeleted(this, new RobotConfigTableRowChangeEvent(((RobotConfigTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.RobotConfigTableRowDeleting != null)) {
                    this.RobotConfigTableRowDeleting(this, new RobotConfigTableRowChangeEvent(((RobotConfigTableRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveRobotConfigTableRow(RobotConfigTableRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                RobotConfig ds = new RobotConfig();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "RobotConfigTableDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class RobotConfigTableRow : global::System.Data.DataRow {
            
            private RobotConfigTableDataTable tableRobotConfigTable;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal RobotConfigTableRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableRobotConfigTable = ((RobotConfigTableDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string RobotID {
                get {
                    try {
                        return ((string)(this[this.tableRobotConfigTable.RobotIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RobotID\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.RobotIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string RobotIP {
                get {
                    try {
                        return ((string)(this[this.tableRobotConfigTable.RobotIPColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RobotIP\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.RobotIPColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int Port1 {
                get {
                    try {
                        return ((int)(this[this.tableRobotConfigTable.Port1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Port1\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.Port1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int Port2 {
                get {
                    try {
                        return ((int)(this[this.tableRobotConfigTable.Port2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Port2\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.Port2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string GPSIP {
                get {
                    try {
                        return ((string)(this[this.tableRobotConfigTable.GPSIPColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'GPSIP\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.GPSIPColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int GPSPort {
                get {
                    try {
                        return ((int)(this[this.tableRobotConfigTable.GPSPortColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'GPSPort\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.GPSPortColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CameraIP {
                get {
                    try {
                        return ((string)(this[this.tableRobotConfigTable.CameraIPColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CameraIP\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.CameraIPColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int CameraPort {
                get {
                    try {
                        return ((int)(this[this.tableRobotConfigTable.CameraPortColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CameraPort\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.CameraPortColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CameraPWD {
                get {
                    try {
                        return ((string)(this[this.tableRobotConfigTable.CameraPWDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CameraPWD\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.CameraPWDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CameraUser {
                get {
                    try {
                        return ((string)(this[this.tableRobotConfigTable.CameraUserColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CameraUser\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.CameraUserColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string AimCameraIP {
                get {
                    try {
                        return ((string)(this[this.tableRobotConfigTable.AimCameraIPColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AimCameraIP\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.AimCameraIPColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int AimCameraPort {
                get {
                    try {
                        return ((int)(this[this.tableRobotConfigTable.AimCameraPortColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AimCameraPort\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.AimCameraPortColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string AimCameraPWD {
                get {
                    try {
                        return ((string)(this[this.tableRobotConfigTable.AimCameraPWDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AimCameraPWD\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.AimCameraPWDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string AimCameraUser {
                get {
                    try {
                        return ((string)(this[this.tableRobotConfigTable.AimCameraUserColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AimCameraUser\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.AimCameraUserColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string IMUIP {
                get {
                    try {
                        return ((string)(this[this.tableRobotConfigTable.IMUIPColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'IMUIP\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.IMUIPColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int IMUPort {
                get {
                    try {
                        return ((int)(this[this.tableRobotConfigTable.IMUPortColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'IMUPort\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.IMUPortColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string LaserRangeIP {
                get {
                    try {
                        return ((string)(this[this.tableRobotConfigTable.LaserRangeIPColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'LaserRangeIP\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.LaserRangeIPColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int LaserRangePort {
                get {
                    try {
                        return ((int)(this[this.tableRobotConfigTable.LaserRangePortColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'LaserRangePort\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.LaserRangePortColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double GoogleEarthStartLat {
                get {
                    try {
                        return ((double)(this[this.tableRobotConfigTable.GoogleEarthStartLatColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'GoogleEarthStartLat\' in table \'RobotConfigTable\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.GoogleEarthStartLatColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double GoogleEarthStartLong {
                get {
                    try {
                        return ((double)(this[this.tableRobotConfigTable.GoogleEarthStartLongColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'GoogleEarthStartLong\' in table \'RobotConfigTable\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.GoogleEarthStartLongColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string RobotType {
                get {
                    try {
                        return ((string)(this[this.tableRobotConfigTable.RobotTypeColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RobotType\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.RobotTypeColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int MotorDir {
                get {
                    try {
                        return ((int)(this[this.tableRobotConfigTable.MotorDirColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MotorDir\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.MotorDirColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int Wheel_CNT {
                get {
                    try {
                        return ((int)(this[this.tableRobotConfigTable.Wheel_CNTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Wheel_CNT\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.Wheel_CNTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double Wheel_R {
                get {
                    try {
                        return ((double)(this[this.tableRobotConfigTable.Wheel_RColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Wheel_R\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.Wheel_RColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double Wheel_DIS {
                get {
                    try {
                        return ((double)(this[this.tableRobotConfigTable.Wheel_DISColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Wheel_DIS\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.Wheel_DISColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double MinDiffPWM {
                get {
                    try {
                        return ((double)(this[this.tableRobotConfigTable.MinDiffPWMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'MinDiffPWM\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.MinDiffPWMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double DrvThrottle {
                get {
                    try {
                        return ((double)(this[this.tableRobotConfigTable.DrvThrottleColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DrvThrottle\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.DrvThrottleColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int TurnDir {
                get {
                    try {
                        return ((int)(this[this.tableRobotConfigTable.TurnDirColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TurnDir\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.TurnDirColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double TurnK {
                get {
                    try {
                        return ((double)(this[this.tableRobotConfigTable.TurnKColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TurnK\' in table \'RobotConfigTable\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRobotConfigTable.TurnKColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRobotIDNull() {
                return this.IsNull(this.tableRobotConfigTable.RobotIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRobotIDNull() {
                this[this.tableRobotConfigTable.RobotIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRobotIPNull() {
                return this.IsNull(this.tableRobotConfigTable.RobotIPColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRobotIPNull() {
                this[this.tableRobotConfigTable.RobotIPColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPort1Null() {
                return this.IsNull(this.tableRobotConfigTable.Port1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPort1Null() {
                this[this.tableRobotConfigTable.Port1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPort2Null() {
                return this.IsNull(this.tableRobotConfigTable.Port2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPort2Null() {
                this[this.tableRobotConfigTable.Port2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsGPSIPNull() {
                return this.IsNull(this.tableRobotConfigTable.GPSIPColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetGPSIPNull() {
                this[this.tableRobotConfigTable.GPSIPColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsGPSPortNull() {
                return this.IsNull(this.tableRobotConfigTable.GPSPortColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetGPSPortNull() {
                this[this.tableRobotConfigTable.GPSPortColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCameraIPNull() {
                return this.IsNull(this.tableRobotConfigTable.CameraIPColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCameraIPNull() {
                this[this.tableRobotConfigTable.CameraIPColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCameraPortNull() {
                return this.IsNull(this.tableRobotConfigTable.CameraPortColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCameraPortNull() {
                this[this.tableRobotConfigTable.CameraPortColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCameraPWDNull() {
                return this.IsNull(this.tableRobotConfigTable.CameraPWDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCameraPWDNull() {
                this[this.tableRobotConfigTable.CameraPWDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCameraUserNull() {
                return this.IsNull(this.tableRobotConfigTable.CameraUserColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCameraUserNull() {
                this[this.tableRobotConfigTable.CameraUserColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsAimCameraIPNull() {
                return this.IsNull(this.tableRobotConfigTable.AimCameraIPColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetAimCameraIPNull() {
                this[this.tableRobotConfigTable.AimCameraIPColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsAimCameraPortNull() {
                return this.IsNull(this.tableRobotConfigTable.AimCameraPortColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetAimCameraPortNull() {
                this[this.tableRobotConfigTable.AimCameraPortColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsAimCameraPWDNull() {
                return this.IsNull(this.tableRobotConfigTable.AimCameraPWDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetAimCameraPWDNull() {
                this[this.tableRobotConfigTable.AimCameraPWDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsAimCameraUserNull() {
                return this.IsNull(this.tableRobotConfigTable.AimCameraUserColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetAimCameraUserNull() {
                this[this.tableRobotConfigTable.AimCameraUserColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsIMUIPNull() {
                return this.IsNull(this.tableRobotConfigTable.IMUIPColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetIMUIPNull() {
                this[this.tableRobotConfigTable.IMUIPColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsIMUPortNull() {
                return this.IsNull(this.tableRobotConfigTable.IMUPortColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetIMUPortNull() {
                this[this.tableRobotConfigTable.IMUPortColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsLaserRangeIPNull() {
                return this.IsNull(this.tableRobotConfigTable.LaserRangeIPColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetLaserRangeIPNull() {
                this[this.tableRobotConfigTable.LaserRangeIPColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsLaserRangePortNull() {
                return this.IsNull(this.tableRobotConfigTable.LaserRangePortColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetLaserRangePortNull() {
                this[this.tableRobotConfigTable.LaserRangePortColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsGoogleEarthStartLatNull() {
                return this.IsNull(this.tableRobotConfigTable.GoogleEarthStartLatColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetGoogleEarthStartLatNull() {
                this[this.tableRobotConfigTable.GoogleEarthStartLatColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsGoogleEarthStartLongNull() {
                return this.IsNull(this.tableRobotConfigTable.GoogleEarthStartLongColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetGoogleEarthStartLongNull() {
                this[this.tableRobotConfigTable.GoogleEarthStartLongColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRobotTypeNull() {
                return this.IsNull(this.tableRobotConfigTable.RobotTypeColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRobotTypeNull() {
                this[this.tableRobotConfigTable.RobotTypeColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsMotorDirNull() {
                return this.IsNull(this.tableRobotConfigTable.MotorDirColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetMotorDirNull() {
                this[this.tableRobotConfigTable.MotorDirColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsWheel_CNTNull() {
                return this.IsNull(this.tableRobotConfigTable.Wheel_CNTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetWheel_CNTNull() {
                this[this.tableRobotConfigTable.Wheel_CNTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsWheel_RNull() {
                return this.IsNull(this.tableRobotConfigTable.Wheel_RColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetWheel_RNull() {
                this[this.tableRobotConfigTable.Wheel_RColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsWheel_DISNull() {
                return this.IsNull(this.tableRobotConfigTable.Wheel_DISColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetWheel_DISNull() {
                this[this.tableRobotConfigTable.Wheel_DISColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsMinDiffPWMNull() {
                return this.IsNull(this.tableRobotConfigTable.MinDiffPWMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetMinDiffPWMNull() {
                this[this.tableRobotConfigTable.MinDiffPWMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDrvThrottleNull() {
                return this.IsNull(this.tableRobotConfigTable.DrvThrottleColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDrvThrottleNull() {
                this[this.tableRobotConfigTable.DrvThrottleColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTurnDirNull() {
                return this.IsNull(this.tableRobotConfigTable.TurnDirColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTurnDirNull() {
                this[this.tableRobotConfigTable.TurnDirColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTurnKNull() {
                return this.IsNull(this.tableRobotConfigTable.TurnKColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTurnKNull() {
                this[this.tableRobotConfigTable.TurnKColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class RobotConfigTableRowChangeEvent : global::System.EventArgs {
            
            private RobotConfigTableRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RobotConfigTableRowChangeEvent(RobotConfigTableRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public RobotConfigTableRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591